### ISSUE TITLE
scan .tex file for \cite{RFCXXXX} commands

### ISSUE THREAD

**Issue by simsong** [iluxonchik/rfc-bibtex#2]
It would be useful to have this tool automatically scan a .tex file to find the RFC commands worth citing.

**Comment by iluxonchik** [comment]
That's a good idea, thank you for the suggestion. Would you like to implement this and then submit a pull request? If so, I will assign this issue to you.

The idea is pretty simple (rough draft):

1. Open .tex file
2. Regex all occurrences of \cite{RFCXXXX}
3. Make sure that there are no duplicates (*e.g.* put them all in a set)
4. Assign the RFC `id`s iterable to `self._id_names`
5. Call `generate_bibtex()` as usual.

A new command line option of parsing all occurrences in a `.tex` file should also be added to `parser.py`
(perhaps `-e`/`--extract`, as in "extract all RFCs IDs from a `.tex` file)?.

If no, I will do this today or tomorrow.

**Comment by simsong** [comment]
Sure. I actually implemented it last night as a different file; I’ll fold it on over the weekend.


----
Sent from my phone.

On Sep 18, 2018, at 3:34 AM, ILLYA Gerasymchuk <notifications@github.com> wrote:

That's a good idea, thank you for the suggestion. Would you like to implement this and then submit a pull request? If so, I will assign this issue to you.

The idea is pretty simple (rough draft):

Open .tex file
Regex all occurrences of \cite{RFCXXXX}
Make sure that there are no duplicates (e.g. put them all in a set)
Assign the RFC ids iterable to self._id_names
Call generate_bibtex() as usual.
A new command line option of parsing all occurrences in a .tex file should also be added to parser.py
(perhaps -e/--extract, as in "extract all RFCs IDs from a .tex file)?.

**Comment by iluxonchik** [comment]
@simsong great, thank you!

**Comment by simsong** [comment]
Actually, the LaTeX way is to read from from the .aux file. Let me try that....


----
Sent from my phone.

On Sep 18, 2018, at 3:34 AM, ILLYA Gerasymchuk <notifications@github.com> wrote:

That's a good idea, thank you for the suggestion. Would you like to implement this and then submit a pull request? If so, I will assign this issue to you.

The idea is pretty simple (rough draft):

Open .tex file
Regex all occurrences of \cite{RFCXXXX}
Make sure that there are no duplicates (e.g. put them all in a set)
Assign the RFC ids iterable to self._id_names
Call generate_bibtex() as usual.
A new command line option of parsing all occurrences in a .tex file should also be added to parser.py
(perhaps -e/--extract, as in "extract all RFCs IDs from a .tex file)?.

**Comment by iluxonchik** [comment]
closed in #12
