### ISSUE TITLE
Choice of sysnetgrp.no-ip.org as a RFC service

### ISSUE THREAD

**Issue by simsong** [iluxonchik/rfc-bibtex#4]
I propose changing the URL service to `https://datatracker.ietf.org/doc/rfc###/bibtex/`, which is the official location for getting this kind of information.

**Comment by simsong** [comment]
For example, `https://datatracker.ietf.org/doc/rfc1/bibtex/` will retrieve RFC1 BiBTeX, and `https://datatracker.ietf.org/doc/draft-tls-certieee1609/bibtex/` will retrieve the BiBTeX for the specified internet draft.

**Comment by iluxonchik** [comment]
Thank you, that sounds like a change that makes sense.

**Comment by simsong** [comment]
Okay. I'll make the change in my code, along with the other changes, and issue a new pull request.

**Comment by iluxonchik** [comment]
closed in #12
