### ISSUE TITLE
rfc-bibtex should not install three executables

### ISSUE THREAD

**Issue by simsong** [iluxonchik/rfc-bibtex#5]
Currently, rfcbibtex installs three executables, each of them identical:

* `rfc_bibtex`
* `rfcbibtex`
* `rfc-bibtex`

This is unnecessary and may cause maintenance problems down the line. The program should install a single executable.

**Comment by iluxonchik** [comment]
Yes, you are right. Which one do you think should be kept? Maybe `rfcbibtex` (although the name is kind of long)? Maybe some other variation?

**Comment by simsong** [comment]
I think `rfcbibtex`.

**Comment by iluxonchik** [comment]
> I think `rfcbibtex`.

I agree, let's keep this one only.
