### ISSUE TITLE
_generate_bibtex_to_file and _generate_bibtex_to_stdout are redundant

### ISSUE THREAD

**Issue by simsong** [iluxonchik/rfc-bibtex#9]
These two functions are nearly identical. It would make more sense to have this be a function that takes either an open `_out_file_name` or `sys.stdout`.

**Comment by iluxonchik** [comment]
You are correct :smile: After completing #6 , some refactoring to the code will have to be done. I wrote this  to quickly address a time-sensitive need, so I wasn't too worried about code quality.

**Comment by iluxonchik** [comment]
closed in #12
